import type { Metadata } from "next"; import { LegalDocument,type LegalSection } from "@/components/legal-document";
export const metadata:Metadata={title:"Privacidad | Listoficios",description:"Borrador de privacidad de Listoficios."};
const sections:LegalSection[]=[
{id:"alcance",title:"Alcance y responsable",content:<p>Esta política explica el tratamiento previsto para visitantes, personas con cuenta y profesionales. La identidad y los canales formales del responsable se incorporarán antes del lanzamiento público.</p>},
{id:"datos",title:"Datos que tratamos",content:<><p>La demo puede guardar nombre, correo, verificador criptográfico de contraseña, datos profesionales, WhatsApp, zonas, favoritos, contactos iniciados y consultas de soporte.</p><p>No guardamos contraseñas en texto plano, DNI, documentos ni archivos sensibles.</p></>},
{id:"finalidades",title:"Finalidad y consentimiento",content:<p>Los datos se usan para demostrar cuentas locales, crear publicaciones, guardar favoritos, registrar actividad de contacto y brindar soporte futuro. No se usa GPS en esta etapa.</p>},
{id:"almacenamiento",title:"Almacenamiento local",content:<p>Los datos funcionales viven en localStorage o sessionStorage del navegador. No se envían a un servidor ni se sincronizan entre dispositivos. Limpiar los datos del sitio los elimina.</p>},
{id:"proveedores",title:"Proveedores futuros",content:<p>Una versión operativa podrá usar infraestructura, correo, mapas, analítica o moderación. Cada integración será documentada antes de recibir datos reales.</p>},
{id:"derechos",title:"Conservación, seguridad y derechos",content:<p>Se definirán plazos y canales para acceso, rectificación y supresión. La versión productiva incorporará controles de acceso, cifrado en tránsito y respuesta a incidentes.</p>},
{id:"normativa",title:"Marco normativo",content:<p>El borrador toma como referencia la <a href="https://www.argentina.gob.ar/normativa/nacional/ley-25326-64790/actualizacion">Ley 25.326</a> y el <a href="https://www.argentina.gob.ar/normativa/nacional/70368/actualizacion">Decreto 1558/2001</a>.</p>}
]; export default function PrivacyPage(){return <LegalDocument kind="Privacidad" title="Tus datos deben tener un propósito claro." copy="Explicamos qué guarda esta demo, por qué y qué cambiará antes de operar con datos reales." sections={sections}/>;}
