import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProfileActions } from "@/components/profile-actions";
import { Icon } from "@/components/icons";
import { getProfessionalBySlug, getServiceBySlug } from "@/data/professionals";
import { formatPrice } from "@/lib/mock-data";

export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string;serviceSlug:string}>}):Promise<Metadata>{const value=await params;const result=await getServiceBySlug(value.slug,value.serviceSlug);return result?{title:`${result.service.title} · ${result.profile.displayName} | Listoficios`,description:result.service.description,alternates:{canonical:`/profesionales/${value.slug}/servicios/${value.serviceSlug}`}}:{}}
export default async function ServiceDetailPage({params}:{params:Promise<{slug:string;serviceSlug:string}>}){const value=await params;const [result,card]=await Promise.all([getServiceBySlug(value.slug,value.serviceSlug),getProfessionalBySlug(value.slug)]);if(!result||!card)notFound();return <main className="px-4 py-10 sm:px-6 lg:px-8 lg:py-16"><div className="mx-auto max-w-[1050px]"><Link href={`/profesionales/${value.slug}`} className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--brand)]"><Icon name="arrow-left" className="size-4"/> Volver al perfil</Link><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_330px]"><article className="rounded-[30px] border border-[var(--line)] bg-white p-7 sm:p-10"><p className="section-kicker">Servicio publicado</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-5xl">{result.service.title}</h1><p className="mt-3 text-sm font-medium text-[var(--brand)]">Por {result.profile.displayName}</p><p className="mt-8 text-base leading-7 text-[var(--muted)]">{result.service.description}</p><div className="mt-7 flex flex-wrap gap-2">{result.service.categories.map((category)=><Link key={category} href={`/servicios/${category}`} className="rounded-full bg-[#eaf4f0] px-3 py-2 text-xs font-semibold text-[var(--brand)]">{category}</Link>)}</div></article><aside className="rounded-[28px] border border-[var(--line)] bg-white p-6 lg:self-start"><p className="text-xs text-[var(--muted)]">Precio orientativo</p><p className="mt-1 text-2xl font-semibold">{formatPrice(result.service.pricingMode,result.service.priceAmount)}</p><div className="my-5 h-px bg-[var(--line)]"/><ProfileActions profile={card}/></aside></div></div></main>}
