import { z } from "zod";
import { requirePermission } from "@/lib/auth-server";
import { createAdminClient } from "@/lib/supabase/admin";
import { apiData, apiError, requestId } from "@/lib/server/api-response";
import { normalizeModerationText } from "@/lib/server/moderation";

const ruleSchema = z.object({ id: z.uuid().optional(), term: z.string().trim().min(2).max(120), matchType: z.enum(["word", "phrase"]), action: z.enum(["review", "block"]), category: z.string().trim().min(2).max(40), scopes: z.array(z.enum(["profile", "service", "review", "support", "report"])).min(1), active: z.boolean().default(true) });
async function access(request: Request) { try { return { session: await requirePermission("catalogs:write") }; } catch { return { response: apiError("FORBIDDEN", "Solo un administrador puede gestionar reglas.", 403, requestId(request)) }; } }
export async function GET(request: Request) { const auth = await access(request); if (auth.response) return auth.response; const result = await createAdminClient().from("moderation_rules").select("*").order("created_at", { ascending: false }); if (result.error) return apiError("DATABASE_ERROR", "No pudimos cargar las reglas.", 503, requestId(request)); return apiData(result.data, { requestId: requestId(request) }); }
async function write(request: Request) { const id = requestId(request); const auth = await access(request); if (auth.response) return auth.response; const parsed = ruleSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return apiError("VALIDATION_ERROR", "Revisá la regla.", 422, id, z.flattenError(parsed.error).fieldErrors); const values = { term: parsed.data.term, normalized_term: normalizeModerationText(parsed.data.term), match_type: parsed.data.matchType, action: parsed.data.action, category: parsed.data.category, scopes: parsed.data.scopes, active: parsed.data.active, created_by: auth.session!.user.id, updated_at: new Date().toISOString() }; const query = parsed.data.id ? createAdminClient().from("moderation_rules").update(values).eq("id", parsed.data.id) : createAdminClient().from("moderation_rules").insert(values); const result = await query.select().single(); if (result.error) return apiError("DATABASE_ERROR", "No pudimos guardar la regla.", 422, id); return apiData(result.data, { requestId: id }, { status: parsed.data.id ? 200 : 201 }); }
export const POST = write; export const PATCH = write;
export async function DELETE(request: Request) { const id = requestId(request); const auth = await access(request); if (auth.response) return auth.response; const ruleId = new URL(request.url).searchParams.get("id"); if (!ruleId || !z.uuid().safeParse(ruleId).success) return apiError("INVALID_ID", "Regla inválida.", 400, id); const result = await createAdminClient().from("moderation_rules").update({ active: false, updated_at: new Date().toISOString() }).eq("id", ruleId); if (result.error) return apiError("DATABASE_ERROR", "No pudimos retirar la regla.", 422, id); return apiData({ retired: true }, { requestId: id }); }
