import sharp from "sharp";
import { z } from "zod";
import { requirePermission } from "@/lib/auth-server";
import { createAdminClient } from "@/lib/supabase/admin";
import { apiData, apiError, requestId } from "@/lib/server/api-response";
import { deleteImage, uploadImage } from "@/lib/server/storage";

export const runtime = "nodejs";
const kinds = z.enum(["logo", "logo_compact", "favicon", "pwa_icon", "open_graph", "hero"]); const allowed = new Set(["image/jpeg", "image/png", "image/webp"]);
async function access() { return requirePermission("site:write"); }
export async function GET(request: Request) { const id = requestId(request); try { await access(); } catch { return apiError("FORBIDDEN", "No tenés acceso a los archivos de marca.", 403, id); } const result = await createAdminClient().from("site_assets").select("*").order("created_at", { ascending: false }); if (result.error) return apiError("DATABASE_ERROR", "No pudimos cargar los archivos.", 503, id); return apiData(result.data, { requestId: id }); }
export async function POST(request: Request) { const id = requestId(request); let session; try { session = await access(); } catch { return apiError("FORBIDDEN", "No tenés acceso a los archivos de marca.", 403, id); } const form = await request.formData().catch(() => null); const file = form?.get("file"); const kind = kinds.safeParse(form?.get("kind")); if (!(file instanceof File) || !kind.success) return apiError("VALIDATION_ERROR", "Seleccioná un archivo y su uso.", 422, id); if (file.size > 3 * 1024 * 1024 || !allowed.has(file.type)) return apiError("INVALID_FILE", "Usá PNG, JPEG o WebP de hasta 3 MB.", 422, id); let publicId: string | null = null; try { const input = Buffer.from(await file.arrayBuffer()); const output = await sharp(input).rotate().resize({ width: 2400, height: 1600, fit: "inside", withoutEnlargement: true }).webp({ quality: 88 }).toBuffer({ resolveWithObject: true }); const stored = await uploadImage(output.data, "listoficios/site-assets"); publicId = stored.publicId; const result = await createAdminClient().from("site_assets").insert({ kind: kind.data, storage_key: stored.publicId, alt: String(form?.get("alt") ?? "").slice(0, 160), width: stored.width, height: stored.height, bytes: stored.bytes, created_by: session.user.id }).select().single(); if (result.error) throw result.error; publicId = null; return apiData(result.data, { requestId: id }, { status: 201 }); } catch { if (publicId) await deleteImage(publicId).catch(() => undefined); return apiError("ASSET_ERROR", "No pudimos procesar el archivo.", 503, id); } }
export async function DELETE(request: Request) { const id = requestId(request); try { await access(); } catch { return apiError("FORBIDDEN", "No tenés acceso a los archivos de marca.", 403, id); } const assetId = new URL(request.url).searchParams.get("id"); if (!assetId || !z.uuid().safeParse(assetId).success) return apiError("INVALID_ID", "Archivo inválido.", 400, id); const supabase = createAdminClient(); const row = await supabase.from("site_assets").select("storage_key").eq("id", assetId).maybeSingle(); if (row.error || !row.data) return apiError("NOT_FOUND", "No encontramos el archivo.", 404, id); const deleted = await supabase.from("site_assets").delete().eq("id", assetId); if (deleted.error) return apiError("ASSET_IN_USE", "El archivo está en uso o no se puede eliminar.", 422, id); await deleteImage(row.data.storage_key).catch(() => undefined); return apiData({ deleted: true }, { requestId: id }); }
