import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { adminOverview } from "@/data/admin";
import { requireAdminSession } from "@/lib/auth-server";

export const metadata:Metadata={title:"Administración | Listoficios"};
export const dynamic="force-dynamic";
export default async function AdminPage(){try{await requireAdminSession();}catch{redirect("/panel");}const data=await adminOverview();const cards=[['Cuentas',data.counts.users],['Perfiles',data.counts.profiles],['Opiniones pendientes',data.counts.pendingReviews],['Reportes abiertos',data.counts.openReports],['Soporte abierto',data.counts.openSupport]];return <main className="px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1180px]"><p className="section-kicker">Operación</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">Panel administrador</h1><p className="mt-3 text-sm text-[var(--muted)]">Moderación reactiva, soporte y estado general de la plataforma.</p><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[var(--line)] bg-white p-5"><p className="text-xs text-[var(--muted)]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</div><div className="mt-8 grid gap-6 lg:grid-cols-3"><AdminList title="Opiniones recientes" rows={data.reviews.map((item)=>({id:item.id,label:item.title,state:item.status}))}/><AdminList title="Reportes recientes" rows={data.reports.map((item)=>({id:item.id,label:item.reason,state:item.status}))}/><AdminList title="Consultas recientes" rows={data.support.map((item)=>({id:item.id,label:`${item.number} · ${item.topic}`,state:item.status}))}/></div></div></main>}
function AdminList({title,rows}:{title:string;rows:{id:string;label:string;state:string}[]}){return <section className="rounded-[26px] border border-[var(--line)] bg-white p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 grid gap-2">{rows.length?rows.map((row)=><div key={row.id} className="rounded-xl bg-[var(--paper)] p-3"><p className="truncate text-sm font-medium">{row.label}</p><p className="mt-1 text-xs capitalize text-[var(--muted)]">{row.state}</p></div>):<p className="py-8 text-center text-sm text-[var(--muted)]">Sin elementos pendientes.</p>}</div></section>}
