"use client";

import { useState } from "react";
import type { AdminListRow } from "@/data/admin-console";

export function ModerationQueue({ initialRows }: { initialRows: AdminListRow[] }) {
  const [rows, setRows] = useState(initialRows); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function decide(id: string, decision: "approved" | "rejected" | "changes_requested") { const reason = decision === "approved" ? "El contenido cumple las pautas de publicación." : prompt("Indicá un motivo claro para el usuario:")?.trim(); if (!reason) return; if (decision !== "approved" && !confirm("Esta decisión afectará el contenido visible. ¿Continuar?")) return; setBusy(id); const response = await fetch(`/api/v1/admin/moderation/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision, reason }) }); const payload = await response.json(); if (response.ok) { setRows((current) => current.filter((row) => row.id !== id)); setMessage("Decisión guardada y auditada."); } else setMessage(payload.error?.message ?? "No pudimos guardar la decisión."); setBusy(null); }
  return <div className="mt-7 grid gap-4">{rows.length === 0 ? <div className="rounded-[22px] border border-dashed border-[var(--line)] bg-white p-10 text-center"><h2 className="font-semibold">La cola está al día</h2><p className="mt-2 text-sm text-[var(--muted)]">No hay contenido pendiente de revisión.</p></div> : rows.map((row) => <article key={String(row.id)} className="rounded-[22px] border border-[var(--line)] bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#edf4f1] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--brand)]">{String(row.target_type)}</span><span className="rounded-full bg-[#f5f5f0] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.1em] text-[var(--muted)]">{String(row.priority)}</span></div><h2 className="mt-3 font-semibold">Caso {String(row.id).slice(0, 8)}</h2><pre className="mt-3 max-h-40 max-w-2xl overflow-auto whitespace-pre-wrap rounded-xl bg-[#f6f8f6] p-3 text-xs leading-5 text-[#52635d]">{JSON.stringify(row.payload_snapshot, null, 2)}</pre></div><div className="flex shrink-0 flex-wrap gap-2 sm:max-w-[210px] sm:flex-col"><button disabled={busy === row.id} onClick={() => void decide(String(row.id), "approved")} className="primary-button !min-h-10 !px-4">Aprobar</button><button disabled={busy === row.id} onClick={() => void decide(String(row.id), "changes_requested")} className="secondary-button !min-h-10 !px-4">Pedir cambios</button><button disabled={busy === row.id} onClick={() => void decide(String(row.id), "rejected")} className="min-h-10 rounded-full border border-red-200 px-4 text-sm font-semibold text-red-700">Rechazar</button></div></div></article>)}{message ? <p role="status" className="text-sm text-[var(--brand)]">{message}</p> : null}</div>;
}
