import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProfessionalCard } from "@/components/professional-card";
import { Icon } from "@/components/icons";
import { listProfessionals } from "@/data/professionals";
import { categories } from "@/lib/mock-data";

export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const slug=(await params).slug;const category=categories.find((item)=>item.id===slug);return category?{title:`${category.name} en Bella Vista | Listoficios`,description:category.description,alternates:{canonical:`/servicios/${category.id}`}}:{}}
export default async function ServiceCategoryPage({params}:{params:Promise<{slug:string}>}){const slug=(await params).slug;const category=categories.find((item)=>item.id===slug);if(!category)notFound();const result=await listProfessionals({category:slug,limit:30});return <main><section className="border-b border-[var(--line)] bg-[var(--paper)] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1100px]"><Link href="/servicios" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--brand)]"><Icon name="arrow-left" className="size-4"/> Todos los servicios</Link><p className="section-kicker mt-8">Servicio local</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em] sm:text-6xl">{category.name} en Bella Vista</h1><p className="mt-4 max-w-2xl text-base leading-7 text-[var(--muted)]">{category.description}. Compará información, zonas y precios orientativos antes de contactar.</p></div></section><section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1100px]">{result.data.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{result.data.map((professional)=><ProfessionalCard key={professional.id} professional={professional}/>)}</div>:<div className="rounded-[26px] border border-dashed border-[var(--line)] p-12 text-center"><h2 className="text-xl font-semibold">Todavía no hay publicaciones en esta categoría</h2><Link href="/profesionales/crear-perfil" className="primary-button mt-5">Publicar este servicio</Link></div>}</div></section></main>}
